# Generated by Django 4.2.23 on 2025-08-05 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('breakdown', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='ai_model_used',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('original', 'Original Upload'), ('breakdown', 'AI Breakdown'), ('report', 'Generated Report'), ('comparison', 'Comparison Analysis'), ('export', 'Exported File')], default='original', max_length=20),
        ),
        migrations.AddField(
            model_name='document',
            name='generation_method',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='document',
            name='parent_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generated_files', to='breakdown.document'),
        ),
    ]
