# Generated by Django 4.2.23 on 2025-08-28 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("breakdown", "0002_document_ai_model_used_document_document_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="breakdown",
            name="step_by_step_content",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="breakdown",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("ready", "Ready"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("reviewed", "Reviewed"),
                    ("finalized", "Finalized"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="status",
            field=models.CharField(
                choices=[
                    ("uploaded", "Uploaded"),
                    ("processing", "Processing"),
                    ("ready_for_ai", "Ready For AI"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="uploaded",
                max_length=20,
            ),
        ),
    ]
