# Generated by Django 4.2.23 on 2025-08-28 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("breakdown", "0003_breakdown_step_by_step_content_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="extraction_map",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
