# Generated by Django 4.2.23 on 2025-08-28 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('breakdown', '0004_document_extraction_map'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=1)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('pointers', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('breakdown', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='breakdown.breakdown')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
