# Generated by Django 4.2.23 on 2025-08-28 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breakdown', '0005_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='breakdown',
            name='document_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='section',
            name='short_summary',
            field=models.TextField(blank=True),
        ),
    ]
