# Generated by Django 4.2.23 on 2025-08-28 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('breakdown', '0007_howto'),
    ]

    operations = [
        migrations.CreateModel(
            name='QAEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('section', 'Section'), ('neighbors', 'Section+Neighbors'), ('document', 'Whole Document')], default='section', max_length=16)),
                ('question', models.TextField()),
                ('answer', models.TextField(blank=True)),
                ('citations', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('breakdown', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qa_entries', to='breakdown.breakdown')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qa_entries', to='breakdown.section')),
            ],
        ),
    ]
