# Generated by Django 4.2.23 on 2025-08-29 12:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("breakdown", "0009_revision"),
    ]

    operations = [
        migrations.CreateModel(
            name="Annotation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "annotation_type",
                    models.CharField(
                        choices=[
                            ("highlight", "Highlight"),
                            ("comment", "Comment"),
                            ("sticky_note", "Sticky Note"),
                            ("redaction", "Redaction"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "start_offset",
                    models.IntegerField(
                        help_text="Character offset where annotation starts (inclusive)"
                    ),
                ),
                (
                    "end_offset",
                    models.IntegerField(
                        help_text="Character offset where annotation ends (exclusive)"
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True,
                        help_text="Text content for comments and sticky notes",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#ffff00",
                        help_text="Hex color code for UI display",
                        max_length=7,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="annotations",
                        to="breakdown.document",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who created this annotation",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["start_offset", "created_at"],
                "indexes": [
                    models.Index(
                        fields=["document", "start_offset", "end_offset"],
                        name="breakdown_a_documen_3230a9_idx",
                    ),
                    models.Index(
                        fields=["document", "user"],
                        name="breakdown_a_documen_c8dd2b_idx",
                    ),
                    models.Index(
                        fields=["annotation_type"],
                        name="breakdown_a_annotat_174c58_idx",
                    ),
                ],
            },
        ),
    ]
